services:
  db:
    image: postgres:17-alpine
    container_name: zaman_db
    restart: always
    env_file: .env
    environment:
      - TZ=Asia/Tehran
      - PGTZ=Asia/Tehran
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zaman_admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: zaman_backend
    restart: always
    env_file: .env
    environment:
      - TZ=Asia/Tehran
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: zaman_frontend
    restart: always
    environment:
      - TZ=Asia/Tehran
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 1G

  nginx:
    image: nginx:alpine
    container_name: zaman_nginx
    restart: always
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Tehran
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend