services:
  # 1. Database Service
  db:
    image: postgres:18-alpine
    container_name: zaman_db
    restart: always
    env_file: .env
    volumes:
      # This saves your data to a folder named 'postgres_data' on your computer
      # so you don't lose data when you restart docker.
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zaman_admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Backend Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: zaman_backend
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  # 3. Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # We must pass this as a build argument so Next.js 'bakes' it into the JS
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: zaman_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend